### ISSUE TITLE
BCTabBarController leaks first selected view controller

### ISSUE THREAD

**Issue by ikershaw** [briancollins/BCTabBarController#11]
I managed to resolve this with a 

```
[selectedViewController release];
```

at line 34 of BCTabBarController.

**Comment by briancollins** [comment]
BCTabBarController uses automatic reference counting (ARC). You need to enable it or it will obviously leak everywhere because there are no release calls

**Comment by ikershaw** [comment]
Ah, sorry, I see the version I'm referring to is from before you refactored to non-ARC. I thought we we're using latest version - I'll update. Thanks.
