### ISSUE TITLE
There is lexical or preprocessor issue, 'BCTabBarController.h' file not found.

### ISSUE THREAD

**Issue by pempeklenjer** [briancollins/BCTabBarController#14]
I've done all steps in Usage section  except the second step, because I did not see any box to be checked.
As written in http://www.section42.de/2011/04/12/bctabbarcontroller-and-xcode-4/ , I should see the entry “libBCTabBarController.a” in the left pane of XCode.
But now I can't find the entry “libBCTabBarController.a” in there. 

As the result, I can't do 
  #import "BCTabBarController.h"
in my delegate.m file. There is lexical or preprocessor issue, 'BCTabBarController.h' file not found.
But I can do 
  @class BCTabBarController; 
from my delegate.h file

Did I miss something?
## 

Usage

Add BCTabBarController.xcodeproj to your project by dragging it into the Groups & Files sidebar.
Select the added project file in the sidebar and then check the box next to libBCTabBarController.a
Select your project's target and right-click and choose "Get Info"
Click the + icon underneath Direct Dependencies and add the BCTabBarController target
libBCTabBarController.a should already be in the list of Linked Libraries
Drag BCTabBarController.bundle into your project's resources
If you haven't already, add the QuartzCore and Core Graphics frameworks to your project
Define the method - (NSString *)iconImageName in each view controller that you add to the tab bar. It should return the filename of the grey tab icon (see creation steps below)
See the example target for usage

**Comment by briancollins** [comment]
Not a bug
