### ISSUE TITLE
Icons are too large for landscape mode

### ISSUE THREAD

**Issue by steipete** [briancollins/BCTabBarController#2]
Either we provide a way to replace them with landscap-y icons or just shrink them programmatically if no -landscape.png file is found.

see screenshot: https://skitch.com/steipetee/r8cqk/ios-simulator

**Comment by briancollins** [comment]
I have other projects right now, but will come back to this issue. If anyone could fix it in the meantime that would be appreciated.

**Comment by briancollins** [comment]
I don't like the idea of shrinking them programatically because they get blurry.

**Comment by steipete** [comment]
me neither, but it would be a fallback.

thanks, if i use that in one of the next projects, i'll add it.

**Comment by dlinsin** [comment]
I implemented your idea of using -landscape for smaller icons. See https://github.com/briancollins/BCTabBarController/pull/3

**Comment by steipete** [comment]
great, thanks
