### ISSUE TITLE
Eliminate the need of two images per tab

### ISSUE THREAD

**Issue by myell0w** [briancollins/BCTabBarController#4]
Take a look at what Peter Boctor does in his custom implementation, there you can find code how to do the blue overlay programatically, would be a huge improvement.

https://github.com/boctor/idev-recipes/blob/master/CustomTabBar/Classes/CustomTabBar.m

**Comment by briancollins** [comment]
I disagree that it would be a huge improvement. Having a separate selected image gives more creative control to the designer to make small tweaks. Though it would be nice to have this programmatic implementation as a fallback for when the selected image state isn't present. I'd be grateful if you could apply Peter's code to this project and issue a pull request.

Thanks

**Comment by myell0w** [comment]
A fallback would be a good option, similar to the -landscape case. I will apply Peter's code if I use BCTabBarController in one of my projects and find time for it, unless then I just wanted to create this issue, maybe someone else has the time to apply these changes.

**Comment by briancollins** [comment]
Thanks, anyone is welcome to attempt this. I'll pull the code in later if I get a chance and someone else doesn't do it first.
