### ISSUE TITLE
Black screen when switching out UITabBarController with BCTabBarController

### ISSUE THREAD

**Issue by tamoyal** [briancollins/BCTabBarController#5]
I switched out the standard UITabBarController with your's and I just get a blank screen.  I'm starting to dig through the code but wondering if you have seen this before.  For some reason in the "loadView" method I get null for the applicationFrame:

NSLog(@"[[UIScreen mainScreen] applicationFrame] = %@", [[UIScreen mainScreen] applicationFrame]);
// prints null
    NSLog(@"[[UIScreen mainScreen] applicationFrame].size.width = %d", [[UIScreen mainScreen] applicationFrame].size.width);
// prints 0

**Comment by runmad** [comment]
I initially had the same issue, but adding:
- (NSString *)iconImageName {
  return @"magnifying-glass.png";
  }

to all UIViewController classes solved it. Oddly enough, it ran fine without this method in Simulator, but the screen was blank on the device without it.
