### ISSUE TITLE
viewWillAppear, viewDidAppear getting called twice

### ISSUE THREAD

**Issue by khuffie** [briancollins/BCTabBarController#7]
At first I suspected it was the way my application was setup, but I created a test application using the EXViewController and generated the BCTabBarController in my app delegate, and I get viewWillAppear and viewDidAppear triggered twice.

Any thoughts?

**Comment by khuffie** [comment]
I noticed that this issue only seems to be present in iOS 5, both on the device and the simulator.

**Comment by briancollins** [comment]
I will update for iOS 5 when it is released. Can't install the beta SDK ATM because it will interfere with client projects.
