### ISSUE TITLE
Blurry icons

### ISSUE THREAD

**Issue by geestring** [briancollins/BCTabBarController#8]
I'm trying to implement the tab bar but some, not all, of the icons I make come out blurry. I though it was just me. I don't know what is causing it. I'm using the same icon for all my tab bar items just as a test. So, it's the same image but blurry in different tab bar items.

**Comment by geestring** [comment]
Sorry, what exactly does that mean? I'm a beginner :)

**Comment by briancollins** [comment]
It means it's fixed :) the icons were being placed at positions with fractions of a pixel (eg 33.33 across) which caused them to lose crispness. Their position is now rounded down to the nearest pixel.

**Comment by geestring** [comment]
amazing! Sorry, I though you were telling me the way to fix it. 

Thank You
